version: '3'

services:
  postgres:
    image: postgres
    container_name: desafio-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  backend:
    build:
      context: .
      dockerfile: ./back-end/Dockerfile
    container_name: desafio-backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      DATABASE_HOST: postgres

  frontend:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    container_name: desafio-frontend
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3000
      PORT: 4000
