version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  backend:
    build:
      context: ./back-end
      dockerfile: ./docker/Dockerfile.backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      DATABASE_HOST: postgres

  frontend:
    build:
      context: ./front-end
      dockerfile: ./docker/Dockerfile.frontend
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3000
